<?php

namespace Database\Seeders;

use App\Models\CompetencyMaster;
use Illuminate\Database\Seeder;

class CompetencyMasterSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'discipline' => 'Awam',
                'code' => 'A1',
                'domain' => 'Lebuhraya & Pengangkutan',
                'competency_title' => 'Kompetensi Kejuruteraan Jalan',
                'is_active' => true,
            ],
            [
                'discipline' => 'Awam',
                'code' => 'A2',
                'domain' => 'Keselamatan Jalan',
                'competency_title' => 'Kompetensi Keselamatan Jalan',
                'is_active' => true,
            ],
            [
                'discipline' => 'Awam',
                'code' => 'A3',
                'domain' => 'Lapangan Terbang',
                'competency_title' => 'Kompetensi Kejuruteraan Lapangan Terbang',
                'is_active' => true,
            ],
            [
                'discipline' => 'Awam',
                'code' => 'A4',
                'domain' => 'Maritim',
                'competency_title' => 'Kompetensi Kejuruteraan Maritim',
                'is_active' => true,
            ],
            [
                'discipline' => 'Awam',
                'code' => 'A5',
                'domain' => 'Jambatan',
                'competency_title' => 'Kompetensi Kejuruteraan Jambatan',
                'is_active' => true,
            ],
            [
                'discipline' => 'Awam',
                'code' => 'A6',
                'domain' => 'Penyenggaraan Jalan',
                'competency_title' => 'Kompetensi Senggara Fasiliti Jalan',
                'is_active' => true,
            ],
            [
                'discipline' => 'Awam',
                'code' => 'A7',
                'domain' => 'Geoteknik / Cerun',
                'competency_title' => 'Kompetensi Kejuruteraan Cerun',
                'is_active' => true,
            ],
            [
                'discipline' => 'Awam',
                'code' => 'B1',
                'domain' => 'Struktur',
                'competency_title' => 'Kompetensi Struktur Bangunan dan Reka Bentuk Struktur',
                'is_active' => true,
            ],
            [
                'discipline' => 'Awam',
                'code' => 'B2',
                'domain' => 'Kerja Sivil',
                'competency_title' => 'Kompetensi Kerja Sivil',
                'is_active' => true,
            ],
            [
                'discipline' => 'Awam',
                'code' => 'B3',
                'domain' => 'Geoteknik',
                'competency_title' => 'Kompetensi Kejuruteraan Geoteknik',
                'is_active' => true,
            ],
            [
                'discipline' => 'Awam',
                'code' => 'B4',
                'domain' => 'Forensik Struktur',
                'competency_title' => 'Kompetensi Forensik Struktur',
                'is_active' => true,
            ],
            [
                'discipline' => 'Awam',
                'code' => 'B5',
                'domain' => 'Bekalan Air',
                'competency_title' => 'Kompetensi Kejuruteraan Bekalan Air',
                'is_active' => true,
            ],
            [
                'discipline' => 'Awam',
                'code' => 'B6',
                'domain' => 'Pengurusan Air',
                'competency_title' => 'Kompetensi Pengurusan Permintaan Bekalan Air',
                'is_active' => true,
            ],
            [
                'discipline' => 'Mekanikal',
                'code' => 'C1',
                'domain' => 'Akustik & Getaran',
                'competency_title' => 'Kompetensi Kawalan Bunyi dan Getaran',
                'is_active' => true,
            ],
            [
                'discipline' => 'Mekanikal',
                'code' => 'C2',
                'domain' => 'Forensik',
                'competency_title' => 'Kompetensi Kejuruteraan Forensik Mekanikal',
                'is_active' => true,
            ],
            [
                'discipline' => 'Mekanikal',
                'code' => 'C3',
                'domain' => 'Kuari & Loji',
                'competency_title' => 'Kompetensi Kejuruteraan Kuari',
                'is_active' => true,
            ],
            [
                'discipline' => 'Mekanikal',
                'code' => 'C4',
                'domain' => 'Kelestarian Mekanikal',
                'competency_title' => 'Kompetensi Kelestarian Sistem Mekanikal',
                'is_active' => true,
            ],
            [
                'discipline' => 'Mekanikal',
                'code' => 'C5',
                'domain' => 'Keselamatan Kebakaran',
                'competency_title' => 'Kompetensi Sistem Pencegahan Kebakaran',
                'is_active' => true,
            ],
            [
                'discipline' => 'Mekanikal',
                'code' => 'C6',
                'domain' => 'HVAC',
                'competency_title' => 'Kompetensi Sistem Penyaman Udara',
                'is_active' => true,
            ],
            [
                'discipline' => 'Mekanikal',
                'code' => 'C7',
                'domain' => 'Perubatan / Hospital',
                'competency_title' => 'Kompetensi Kejuruteraan Sistem Perubatan',
                'is_active' => true,
            ],
            [
                'discipline' => 'Mekanikal',
                'code' => 'C8',
                'domain' => 'Automasi Bangunan',
                'competency_title' => 'Kompetensi Sistem Automasi dan Kawalan Bangunan (BAS/BMS)',
                'is_active' => true,
            ],
            [
                'discipline' => 'Mekanikal',
                'code' => 'C9',
                'domain' => 'Sanitari & Paip',
                'competency_title' => 'Kompetensi Sistem Bekalan Air Dalaman dan Sanitari',
                'is_active' => true,
            ],
            [
                'discipline' => 'Mekanikal',
                'code' => 'C10',
                'domain' => 'Pengangkutan Menegak',
                'competency_title' => 'Kompetensi Lif dan Eskalator',
                'is_active' => true,
            ],
            [
                'discipline' => 'Mekanikal',
                'code' => 'C11',
                'domain' => 'Operasi Woksyop',
                'competency_title' => 'Kompetensi Pengurusan dan Kejuruteraan Woksyop',
                'is_active' => true,
            ],
            [
                'discipline' => 'Mekanikal',
                'code' => 'C12',
                'domain' => 'Pengurusan Tenaga',
                'competency_title' => 'Kompetensi Sistem Pengurusan Tenaga',
                'is_active' => true,
            ],
            [
                'discipline' => 'Mekanikal',
                'code' => 'C13',
                'domain' => 'Kecekapan Air',
                'competency_title' => 'Kompetensi Sistem Kecekapan Penggunaan Air',
                'is_active' => true,
            ],
            [
                'discipline' => 'Elektrik',
                'code' => 'D1',
                'domain' => 'Sistem Elektrik',
                'competency_title' => 'Kompetensi Electrical System Engineering (ESE)',
                'is_active' => true,
            ],
            [
                'discipline' => 'Elektrik',
                'code' => 'D2',
                'domain' => 'Perlindungan Kilat',
                'competency_title' => 'Kompetensi Lightning and Surge Protection System',
                'is_active' => true,
            ],
            [
                'discipline' => 'Elektrik',
                'code' => 'D3',
                'domain' => 'Keselamatan & Perlindungan',
                'competency_title' => 'Kompetensi Power Protection System and Electrical Safety',
                'is_active' => true,
            ],
            [
                'discipline' => 'Elektrik',
                'code' => 'D4',
                'domain' => 'Kejuruteraan Bioperubatan',
                'competency_title' => 'Kompetensi Biomedical Engineering',
                'is_active' => true,
            ],
            [
                'discipline' => 'Elektrik',
                'code' => 'D5',
                'domain' => 'Kualiti Kuasa',
                'competency_title' => 'Kompetensi Power Quality (Electrical)',
                'is_active' => true,
            ],
            [
                'discipline' => 'Elektrik',
                'code' => 'D6',
                'domain' => 'Forensik Elektrik',
                'competency_title' => 'Kompetensi Forensic Engineering (Electrical)',
                'is_active' => true,
            ],
            [
                'discipline' => 'Elektrik',
                'code' => 'D7',
                'domain' => 'Pencahayaan',
                'competency_title' => 'Kompetensi Illumination Engineering',
                'is_active' => true,
            ],
            [
                'discipline' => 'Elektrik',
                'code' => 'D8',
                'domain' => 'Keselamatan & Kawalan',
                'competency_title' => 'Kompetensi Security System',
                'is_active' => true,
            ],
            [
                'discipline' => 'Elektrik',
                'code' => 'D9',
                'domain' => 'Audio',
                'competency_title' => 'Kompetensi Audio System',
                'is_active' => true,
            ],
            [
                'discipline' => 'Elektrik',
                'code' => 'D10',
                'domain' => 'Visual & Siaran',
                'competency_title' => 'Kompetensi SMATV and Visual System',
                'is_active' => true,
            ],
            [
                'discipline' => 'Elektrik',
                'code' => 'D11',
                'domain' => 'Pusat Data',
                'competency_title' => 'Kompetensi Data Centre and System Design',
                'is_active' => true,
            ],
            [
                'discipline' => 'Elektrik',
                'code' => 'D12',
                'domain' => 'Rangkaian',
                'competency_title' => 'Kompetensi Network System Technologies',
                'is_active' => true,
            ],
            [
                'discipline' => 'Elektrik',
                'code' => 'D13',
                'domain' => 'Telekomunikasi',
                'competency_title' => 'Kompetensi Telecommunication',
                'is_active' => true,
            ],
            [
                'discipline' => 'Elektrik',
                'code' => 'D14',
                'domain' => 'Kecekapan Tenaga',
                'competency_title' => 'Kompetensi Energy Efficiency (Electrical)',
                'is_active' => true,
            ],
            [
                'discipline' => 'Elektrik',
                'code' => 'D15',
                'domain' => 'Tenaga Boleh Baharu',
                'competency_title' => 'Kompetensi Renewable Energy (Electrical)',
                'is_active' => true,
            ],
            [
                'discipline' => 'Arkitek',
                'code' => 'E1',
                'domain' => 'Forensik Arkitektur',
                'competency_title' => 'Kompetensi Forensik Seni Bina',
                'is_active' => true,
            ],
            [
                'discipline' => 'Arkitek',
                'code' => 'E2',
                'domain' => 'Reka Bentuk Dalaman',
                'competency_title' => 'Kompetensi Hiasan Dalaman',
                'is_active' => true,
            ],
            [
                'discipline' => 'Arkitek',
                'code' => 'E3',
                'domain' => 'Konservasi',
                'competency_title' => 'Kompetensi Konservasi Bangunan',
                'is_active' => true,
            ],
            [
                'discipline' => 'Arkitek',
                'code' => 'E4',
                'domain' => 'Multimedia',
                'competency_title' => 'Kompetensi Multimedia Seni Bina',
                'is_active' => true,
            ],
            [
                'discipline' => 'Arkitek',
                'code' => 'E5',
                'domain' => 'Perancangan Khusus',
                'competency_title' => 'Kompetensi Perancangan Fasiliti Kesihatan',
                'is_active' => true,
            ],
            [
                'discipline' => 'Arkitek',
                'code' => 'E6',
                'domain' => 'Keselamatan',
                'competency_title' => 'Kompetensi Perancangan Seni Bina Keselamatan',
                'is_active' => true,
            ],
            [
                'discipline' => 'Arkitek',
                'code' => 'E7',
                'domain' => 'Perbandaran & Lestari',
                'competency_title' => 'Kompetensi Reka Bentuk Perbandaran Lestari',
                'is_active' => true,
            ],
            [
                'discipline' => 'Arkitek',
                'code' => 'E8',
                'domain' => 'Reka Bentuk Sejagat',
                'competency_title' => 'Kompetensi Reka Bentuk Sejagat',
                'is_active' => true,
            ],
            [
                'discipline' => 'Arkitek',
                'code' => 'E9',
                'domain' => 'Landskap',
                'competency_title' => 'Kompetensi Seni Bina Landskap',
                'is_active' => true,
            ],
            [
                'discipline' => 'Arkitek',
                'code' => 'E10',
                'domain' => 'Lestari',
                'competency_title' => 'Kompetensi Seni Bina Lestari',
                'is_active' => true,
            ],
            [
                'discipline' => 'Arkitek',
                'code' => 'E11',
                'domain' => 'Keselamatan Kebakaran',
                'competency_title' => 'Kompetensi Reka Bentuk Kawalan Kebakaran (Arkitektural)',
                'is_active' => true,
            ],
            [
                'discipline' => 'Arkitek',
                'code' => 'E12',
                'domain' => 'Perundangan',
                'competency_title' => 'Kompetensi Perundangan Pemajuan Pembangunan',
                'is_active' => true,
            ],
            [
                'discipline' => 'Ukur Bahan',
                'code' => 'F1',
                'domain' => 'Pengurusan Kos',
                'competency_title' => 'Kompetensi Pengurus Kos Pembinaan Kerja Bangunan',
                'is_active' => true,
            ],
            [
                'discipline' => 'Ukur Bahan',
                'code' => 'F2',
                'domain' => 'Pengurusan Kos',
                'competency_title' => 'Kompetensi Pengurus Kos Pembinaan Kerja Kejuruteraan Awam',
                'is_active' => true,
            ],
            [
                'discipline' => 'Ukur Bahan',
                'code' => 'F3',
                'domain' => 'Pengurusan Kos',
                'competency_title' => 'Kompetensi Pengurus Kos Pembinaan Pengurusan Fasiliti dan Penyenggaraan (FMM)',
                'is_active' => true,
            ],
            [
                'discipline' => 'Ukur Bahan',
                'code' => 'F4',
                'domain' => 'Kontrak & Tuntutan',
                'competency_title' => 'Kompetensi Pengurus Tuntutan Kontrak Kerja',
                'is_active' => true,
            ],
            [
                'discipline' => 'Ukur Bahan',
                'code' => 'F5',
                'domain' => 'Kontrak & Tuntutan',
                'competency_title' => 'Kompetensi Pengurus Pertikaian Kontrak Kerja',
                'is_active' => true,
            ],
            [
                'discipline' => 'Ukur Bahan',
                'code' => 'F6',
                'domain' => 'Perolehan',
                'competency_title' => 'Kompetensi Pengurus Perolehan Kerja',
                'is_active' => true,
            ],
            [
                'discipline' => 'Ukur Bahan',
                'code' => 'F7',
                'domain' => 'Perolehan',
                'competency_title' => 'Kompetensi Pengurus Perolehan Perkhidmatan Perunding',
                'is_active' => true,
            ],
            [
                'discipline' => 'Ukur Bahan',
                'code' => 'F8',
                'domain' => 'Perolehan',
                'competency_title' => 'Kompetensi Pengurus Perolehan Pengurusan Fasiliti dan Penyenggaraan (FMM)',
                'is_active' => true,
            ],
            [
                'discipline' => 'Ukur Bahan',
                'code' => 'F9',
                'domain' => 'Pentadbiran Kontrak',
                'competency_title' => 'Kompetensi Pengurus Pentadbiran Kontrak Kerja',
                'is_active' => true,
            ],
            [
                'discipline' => 'Ukur Bahan',
                'code' => 'F10',
                'domain' => 'Pentadbiran Kontrak',
                'competency_title' => 'Kompetensi Pengurus Pentadbiran Kontrak Perkhidmatan Perunding',
                'is_active' => true,
            ],
            [
                'discipline' => 'Ukur Bahan',
                'code' => 'F11',
                'domain' => 'Pentadbiran Kontrak',
                'competency_title' => 'Kompetensi Pengurus Pentadbiran Kontrak Pengurusan Fasiliti dan Penyenggaraan (FMM)',
                'is_active' => true,
            ],
            [
                'discipline' => 'Ukur Bahan',
                'code' => 'F12',
                'domain' => 'Pengukuran Kuantiti',
                'competency_title' => 'Kompetensi Pengukuran Kuantiti Kerja Bangunan',
                'is_active' => true,
            ],
            [
                'discipline' => 'Ukur Bahan',
                'code' => 'F13',
                'domain' => 'Pengukuran Kuantiti',
                'competency_title' => 'Kompetensi Pengukuran Kuantiti Kerja Kejuruteraan Awam',
                'is_active' => true,
            ],
            [
                'discipline' => 'Pelbagai',
                'code' => 'G1',
                'domain' => 'Pengurusan Aset',
                'competency_title' => 'Kompetensi Pengurusan Aset dan Fasiliti',
                'is_active' => true,
            ],
            [
                'discipline' => 'Pelbagai',
                'code' => 'G2',
                'domain' => 'Pengurusan Aset',
                'competency_title' => 'Kompetensi Penilaian Aset Tak Alih (Bangunan)',
                'is_active' => true,
            ],
            [
                'discipline' => 'Pelbagai',
                'code' => 'H1',
                'domain' => 'Teknologi & Digital (BIM)',
                'competency_title' => 'Kompetensi Building Information Modelling – BIM Modeller',
                'is_active' => true,
            ],
            [
                'discipline' => 'Pelbagai',
                'code' => 'H2',
                'domain' => 'Teknologi & Digital (BIM)',
                'competency_title' => 'Kompetensi Building Information Modelling – BIM Coordinator',
                'is_active' => true,
            ],
            [
                'discipline' => 'Pelbagai',
                'code' => 'H3',
                'domain' => 'Teknologi & Digital (BIM)',
                'competency_title' => 'Kompetensi Building Information Modelling – BIM QS',
                'is_active' => true,
            ],
            [
                'discipline' => 'Pelbagai',
                'code' => 'H4',
                'domain' => 'Teknologi & Digital (BIM)',
                'competency_title' => 'Kompetensi Building Information Modelling – BIM Manager',
                'is_active' => true,
            ],
            [
                'discipline' => 'Pelbagai',
                'code' => 'J',
                'domain' => 'Kelestarian & Alam Sekitar',
                'competency_title' => 'Kompetensi Kelestarian Alam Sekitar',
                'is_active' => true,
            ],
            [
                'discipline' => 'Pelbagai',
                'code' => 'K',
                'domain' => 'Kejuruteraan Khusus',
                'competency_title' => 'Kompetensi Kejuruteraan Pengangkutan Darat',
                'is_active' => true,
            ],
            [
                'discipline' => 'Pelbagai',
                'code' => 'L',
                'domain' => 'Inovasi & R&D',
                'competency_title' => 'Kompetensi Inovasi',
                'is_active' => true,
            ],
            [
                'discipline' => 'Pelbagai',
                'code' => 'M',
                'domain' => 'Pembangunan Modal Insan',
                'competency_title' => 'Kompetensi Penyampaian Latihan',
                'is_active' => true,
            ],
            [
                'discipline' => 'Pelbagai',
                'code' => 'N',
                'domain' => 'Inovasi & R&D',
                'competency_title' => 'Kompetensi Penyelidikan dan Pembangunan',
                'is_active' => true,
            ],
            [
                'discipline' => 'Pelbagai',
                'code' => 'O',
                'domain' => 'Penarafan Hijau (pH JKR)',
                'competency_title' => 'Kompetensi Pemudahcara dan Penilai pH JKR Kategori Bangunan',
                'is_active' => true,
            ],
            [
                'discipline' => 'Pelbagai',
                'code' => 'P',
                'domain' => 'Penarafan Hijau (pH JKR)',
                'competency_title' => 'Kompetensi Pemudahcara dan Penilai pH JKR Kategori Jalan',
                'is_active' => true,
            ],
        ];

        foreach ($items as $item) {
            CompetencyMaster::updateOrCreate(
                ['code' => $item['code']],
                $item
            );
        }
    }
}
