<?php

namespace Database\Seeders;

use App\Models\ExperienceMaster;
use Illuminate\Database\Seeder;

class ExperienceMasterSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'ACMV (Air Conditioning & Mechanical Ventilation)',
                'sub_field' => 'Sistem Penyaman Udara',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Kebakaran',
                'sub_field' => 'Sistem Pencegahan Kebakaran',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Lif',
                'sub_field' => 'Sistem Lif dan Eskalator',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Plumbing',
                'sub_field' => 'Sistem Bekalan Air Dalaman dan Sanitari',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Pengurusan Aset Loji, Jentera & Kenderaan (Woksyop)',
                'sub_field' => 'Pengurusan & Kejuruteraan Woksyop',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Pengurusan Aset Loji, Jentera & Kenderaan (Woksyop)',
                'sub_field' => 'Vehicles (Kenderaan)',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Pengurusan Aset Loji, Jentera & Kenderaan (Woksyop)',
                'sub_field' => 'Kejuruteraan Kuari dan Loji',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Pengurusan Aset Loji, Jentera & Kenderaan (Woksyop)',
                'sub_field' => 'Inspection & Evaluation of vehicles / machineries / equipment',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Pengurusan Aset Loji, Jentera & Kenderaan (Woksyop)',
                'sub_field' => 'Maintenance of vehicles & construction machinery',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Pengurusan Aset Loji, Jentera & Kenderaan (Woksyop)',
                'sub_field' => 'Quarry Operation, Maintenance and Road Surfacing',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Kelestarian & Kepakaran Khusus (Sustainability & Advisory)',
                'sub_field' => 'Kelestarian Sistem Mekanikal',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Kelestarian & Kepakaran Khusus (Sustainability & Advisory)',
                'sub_field' => 'Sistem Pengurusan Tenaga',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Kelestarian & Kepakaran Khusus (Sustainability & Advisory)',
                'sub_field' => 'Sistem Kecekapan Penggunaan Air',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Kelestarian & Kepakaran Khusus (Sustainability & Advisory)',
                'sub_field' => 'Kawalan Bunyi dan Getaran',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Kelestarian & Kepakaran Khusus (Sustainability & Advisory)',
                'sub_field' => 'Kejuruteraan Sistem Perubatan',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Kelestarian & Kepakaran Khusus (Sustainability & Advisory)',
                'sub_field' => 'Mechanical Services Specialist',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Pengurusan Fasiliti Bangunan & Forensik (Facility Management)',
                'sub_field' => 'Sistem Automasi Bangunan',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Pengurusan Fasiliti Bangunan & Forensik (Facility Management)',
                'sub_field' => 'Maintenance of mechanical systems in buildings',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Pengurusan Fasiliti Bangunan & Forensik (Facility Management)',
                'sub_field' => 'Inspection & Evaluation of Mechanical System in Buildings',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Pengurusan Fasiliti Bangunan & Forensik (Facility Management)',
                'sub_field' => 'Kejuruteraan Forensik Mekanikal',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Rekabentuk (Design) & Teknologi Pemodelan',
                'sub_field' => 'Design of Air-Conditioning & Mechanical Ventilation System',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Rekabentuk (Design) & Teknologi Pemodelan',
                'sub_field' => 'Design of Fire Fighting System',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Rekabentuk (Design) & Teknologi Pemodelan',
                'sub_field' => 'Design of Lift, Dumbwaiter & Escalator System',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Rekabentuk (Design) & Teknologi Pemodelan',
                'sub_field' => 'Internal Cold Water, Sanitary Plumbing System & Pumping System',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Rekabentuk (Design) & Teknologi Pemodelan',
                'sub_field' => 'Design of Laboratory & Medical Equipment / Piped Gas System',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Rekabentuk (Design) & Teknologi Pemodelan',
                'sub_field' => 'Design of Miscellaneous Mechanical Services',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Rekabentuk (Design) & Teknologi Pemodelan',
                'sub_field' => 'Building Management System Design',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Rekabentuk (Design) & Teknologi Pemodelan',
                'sub_field' => 'Quarry Design',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Rekabentuk (Design) & Teknologi Pemodelan',
                'sub_field' => 'Building Information Modeling',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Rekabentuk (Design) & Teknologi Pemodelan',
                'sub_field' => 'Mechanical Drawing-Autocad',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Rekabentuk (Design) & Teknologi Pemodelan',
                'sub_field' => 'AI In Mechanical Design',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Pelaksanaan Projek (Project Delivery) & Pengurusan Kontrak',
                'sub_field' => 'D&B Project Implementation Pre Contract (Mechanical)',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Pelaksanaan Projek (Project Delivery) & Pengurusan Kontrak',
                'sub_field' => 'In-House Project Implementation (Mechanical consultant)',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Pelaksanaan Projek (Project Delivery) & Pengurusan Kontrak',
                'sub_field' => 'Consultancy Services (Mechanical)',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Pelaksanaan Projek (Project Delivery) & Pengurusan Kontrak',
                'sub_field' => 'Mechanical Tender Documentation and Evaluation',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Penyeliaan Tapak (Site Supervision) & Pengujian',
                'sub_field' => 'Site supervision for mechanical project',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Penyeliaan Tapak (Site Supervision) & Pengujian',
                'sub_field' => 'Testing & Commissioning of mechanical system',
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Pengurusan Perolehan (Procurement Management)',
                'sub_field' => null,
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Pentadbiran Kontrak (Contract Administration)',
                'sub_field' => null,
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Pengurusan Kos & Kewangan Projek (Cost & Financial Management)',
                'sub_field' => null,
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Tadbir Urus Perolehan & Keurusetiaan (Procurement Governance & Secretariat)',
                'sub_field' => null,
                'is_active' => true,
            ],
            [
                'field_type' => 'Teras Teknikal & Projek',
                'main_field_category' => 'Rekabentuk, Pengurusan Projek, Senggara Fasiliti, Testing & Commissioning, Site Supervision, Inspection, Pelaksanaan Projek & Pembinaan, Bahagian Kontrak dan Ukur Bahan',
                'main_system_category' => 'Pentadbiran Sistem Maklumat Pengurusan (Management Information Systems)',
                'sub_field' => null,
                'is_active' => true,
            ],
            [
                'field_type' => 'Auditan & Pematuhan',
                'main_field_category' => 'Juruaudit Utama, Juruaudit Dalaman / Jabatan, Penyelaras Audit, Auditee',
                'main_system_category' => 'Auditan',
                'sub_field' => 'Auditan Dalaman SPK (Sistem Pengurusan Kualiti)',
                'is_active' => true,
            ],
            [
                'field_type' => 'Auditan & Pematuhan',
                'main_field_category' => 'Juruaudit Utama, Juruaudit Dalaman / Jabatan, Penyelaras Audit, Auditee',
                'main_system_category' => 'Auditan',
                'sub_field' => 'Auditan SPAS (Sistem Pengurusan Alam Sekitar)',
                'is_active' => true,
            ],
            [
                'field_type' => 'Auditan & Pematuhan',
                'main_field_category' => 'Juruaudit Utama, Juruaudit Dalaman / Jabatan, Penyelaras Audit, Auditee',
                'main_system_category' => 'Auditan',
                'sub_field' => 'Auditan SPKKP (Keselamatan & Kesihatan Pekerjaan)',
                'is_active' => true,
            ],
            [
                'field_type' => 'Auditan & Pematuhan',
                'main_field_category' => 'Juruaudit Utama, Juruaudit Dalaman / Jabatan, Penyelaras Audit, Auditee',
                'main_system_category' => 'Auditan',
                'sub_field' => 'Auditan SPAR (Sistem Pengurusan Antirasuah)',
                'is_active' => true,
            ],
            [
                'field_type' => 'Auditan & Pematuhan',
                'main_field_category' => 'Juruaudit Utama, Juruaudit Dalaman / Jabatan, Penyelaras Audit, Auditee',
                'main_system_category' => 'Auditan',
                'sub_field' => 'Penilaian & Auditan EKSA Kendiri',
                'is_active' => true,
            ],
            [
                'field_type' => 'Auditan & Pematuhan',
                'main_field_category' => 'Juruaudit Utama, Juruaudit Dalaman / Jabatan, Penyelaras Audit, Auditee',
                'main_system_category' => 'Auditan',
                'sub_field' => 'Auditan SPT (Sistem Pengurusan Tenaga)',
                'is_active' => true,
            ],
            [
                'field_type' => 'Pengurusan & Pentadbiran',
                'main_field_category' => 'Pengerusi / Ketua Pasukan, Urus Setia / Penyelaras, Ahli Jawatankuasa (AJK), Fasilitator / Penceramah',
                'main_system_category' => 'Pengurusan Kualiti',
                'sub_field' => 'Pelaksanaan Amalan EKSA Kendiri',
                'is_active' => true,
            ],
            [
                'field_type' => 'Pengurusan & Pentadbiran',
                'main_field_category' => 'Pengerusi / Ketua Pasukan, Urus Setia / Penyelaras, Ahli Jawatankuasa (AJK), Fasilitator / Penceramah',
                'main_system_category' => 'Pengurusan Kualiti',
                'sub_field' => 'Kawalan Dokumen, Rekod Bersepadu & Penerbitan Buletin',
                'is_active' => true,
            ],
            [
                'field_type' => 'Pengurusan & Pentadbiran',
                'main_field_category' => 'Pengerusi / Ketua Pasukan, Urus Setia / Penyelaras, Ahli Jawatankuasa (AJK), Fasilitator / Penceramah',
                'main_system_category' => 'Pengurusan Kualiti',
                'sub_field' => 'Penyediaan & Semakan Prosedur Operasi Standard (SOP)',
                'is_active' => true,
            ],
            [
                'field_type' => 'Pengurusan & Pentadbiran',
                'main_field_category' => 'Pengerusi / Ketua Pasukan, Urus Setia / Penyelaras, Ahli Jawatankuasa (AJK), Fasilitator / Penceramah',
                'main_system_category' => 'Pengurusan Kualiti',
                'sub_field' => 'Pelaksanaan Dasar & Objektif Kualiti',
                'is_active' => true,
            ],
            [
                'field_type' => 'Pengurusan & Pentadbiran',
                'main_field_category' => 'Pengerusi / Ketua Pasukan, Urus Setia / Penyelaras, Ahli Jawatankuasa (AJK), Fasilitator / Penceramah',
                'main_system_category' => 'Pentadbiran & Pengurusan Korporat',
                'sub_field' => 'Pengurusan & Urus Setia Mesyuarat',
                'is_active' => true,
            ],
            [
                'field_type' => 'Pengurusan & Pentadbiran',
                'main_field_category' => 'Pengerusi / Ketua Pasukan, Urus Setia / Penyelaras, Ahli Jawatankuasa (AJK), Fasilitator / Penceramah',
                'main_system_category' => 'Pentadbiran & Pengurusan Korporat',
                'sub_field' => 'Pengurusan Acara & Program Rasmi',
                'is_active' => true,
            ],
            [
                'field_type' => 'Pengurusan & Pentadbiran',
                'main_field_category' => 'Pengerusi / Ketua Pasukan, Urus Setia / Penyelaras, Ahli Jawatankuasa (AJK), Fasilitator / Penceramah',
                'main_system_category' => 'Pentadbiran & Pengurusan Korporat',
                'sub_field' => 'Perancangan Strategik & Pelan Bisnes',
                'is_active' => true,
            ],
            [
                'field_type' => 'Pengurusan & Pentadbiran',
                'main_field_category' => 'Pengerusi / Ketua Pasukan, Urus Setia / Penyelaras, Ahli Jawatankuasa (AJK), Fasilitator / Penceramah',
                'main_system_category' => 'Pentadbiran & Pengurusan Korporat',
                'sub_field' => 'Penyelarasan Takwim Cawangan',
                'is_active' => true,
            ],
            [
                'field_type' => 'Pengurusan & Pentadbiran',
                'main_field_category' => 'Pengerusi / Ketua Pasukan, Urus Setia / Penyelaras, Ahli Jawatankuasa (AJK), Fasilitator / Penceramah',
                'main_system_category' => 'Pentadbiran & Pengurusan Korporat',
                'sub_field' => 'Pengurusan & Kemas Kini myPortfolio',
                'is_active' => true,
            ],
            [
                'field_type' => 'Pengurusan & Pentadbiran',
                'main_field_category' => 'Pengerusi / Ketua Pasukan, Urus Setia / Penyelaras, Ahli Jawatankuasa (AJK), Fasilitator / Penceramah',
                'main_system_category' => 'Latihan & Kompetensi',
                'sub_field' => 'Penyelarasan Latihan & Kursus',
                'is_active' => true,
            ],
            [
                'field_type' => 'Pengurusan & Pentadbiran',
                'main_field_category' => 'Pengerusi / Ketua Pasukan, Urus Setia / Penyelaras, Ahli Jawatankuasa (AJK), Fasilitator / Penceramah',
                'main_system_category' => 'Latihan & Kompetensi',
                'sub_field' => 'Pengurusan & Penilaian Kompetensi',
                'is_active' => true,
            ],
            [
                'field_type' => 'Pengurusan & Pentadbiran',
                'main_field_category' => 'Pengerusi / Ketua Pasukan, Urus Setia / Penyelaras, Ahli Jawatankuasa (AJK), Fasilitator / Penceramah',
                'main_system_category' => 'Latihan & Kompetensi',
                'sub_field' => 'Pengurusan Inovasi & Kumpulan Inovatif dan Kreatif (KIK)',
                'is_active' => true,
            ],
            [
                'field_type' => 'Pengurusan & Pentadbiran',
                'main_field_category' => 'Pengerusi / Ketua Pasukan, Urus Setia / Penyelaras, Ahli Jawatankuasa (AJK), Fasilitator / Penceramah',
                'main_system_category' => 'Latihan & Kompetensi',
                'sub_field' => 'Pengurusan Tatatertib & Disiplin',
                'is_active' => true,
            ],
            [
                'field_type' => 'Sistem & Portfolio Projek',
                'main_field_category' => 'Pegawai Pemantau, Pentadbir Sistem',
                'main_system_category' => 'Pengurusan Portfolio Projek',
                'sub_field' => 'Penyelarasan Permohonan Projek (RMK / Rolling Plan)',
                'is_active' => true,
            ],
            [
                'field_type' => 'Sistem & Portfolio Projek',
                'main_field_category' => 'Pegawai Pemantau, Pentadbir Sistem',
                'main_system_category' => 'Pengurusan Portfolio Projek',
                'sub_field' => 'Pemantauan Prestasi Portfolio (SKALA / SPP II / MyProjek)',
                'is_active' => true,
            ],
            [
                'field_type' => 'Sistem & Portfolio Projek',
                'main_field_category' => 'Pegawai Pemantau, Pentadbir Sistem',
                'main_system_category' => 'Pengurusan Portfolio Projek',
                'sub_field' => 'Pemantauan & Pelaporan Peruntukan Kewangan Projek',
                'is_active' => true,
            ],
            [
                'field_type' => 'Sistem & Portfolio Projek',
                'main_field_category' => 'Pegawai Pemantau, Pentadbir Sistem',
                'main_system_category' => 'Pengurusan Portfolio Projek',
                'sub_field' => 'Penyelarasan Mesyuarat Pemantauan Projek (MTPK / Kajian Semula)',
                'is_active' => true,
            ],
        ];

        foreach ($items as $item) {
            ExperienceMaster::updateOrCreate(
                [
                    'field_type' => $item['field_type'],
                    'main_system_category' => $item['main_system_category'],
                    'sub_field' => $item['sub_field'],
                ],
                $item
            );
        }
    }
}
