<?php

namespace Database\Seeders;

use App\Models\HonoraryTitleMaster;
use Illuminate\Database\Seeder;

class HonoraryTitleMasterSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'issuer_category' => 'Persekutuan',
                'issuer' => 'Kerajaan Persekutuan (YDPA)',
                'scope_level' => 'Persekutuan',
                'award_name' => 'Darjah Yang Mulia Setia Mahkota Malaysia (SSM)',
                'prefix_title' => 'Tun',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 1,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Persekutuan',
                'issuer' => 'Kerajaan Persekutuan (YDPA)',
                'scope_level' => 'Persekutuan',
                'award_name' => 'Darjah Yang Mulia Pangkuan Negara (PMN)',
                'prefix_title' => 'Tan Sri',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 2,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Persekutuan',
                'issuer' => 'Kerajaan Persekutuan (YDPA)',
                'scope_level' => 'Persekutuan',
                'award_name' => 'Darjah Yang Mulia Setia Mahkota Malaysia (PSM)',
                'prefix_title' => 'Tan Sri',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 3,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Persekutuan',
                'issuer' => 'Kerajaan Persekutuan (YDPA)',
                'scope_level' => 'Persekutuan',
                'award_name' => 'Darjah Pangkuan Negara (PJN)',
                'prefix_title' => 'Datuk',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 4,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Persekutuan',
                'issuer' => 'Kerajaan Persekutuan (YDPA)',
                'scope_level' => 'Persekutuan',
                'award_name' => 'Darjah Diraja Tertinggi / Panglima Jasa Negara (PSD)',
                'prefix_title' => 'Datuk',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 5,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Persekutuan',
                'issuer' => 'Kerajaan Persekutuan (YDPA)',
                'scope_level' => 'Persekutuan (Kepujian/Tanpa Gelaran)',
                'award_name' => 'Johan Mangku Negara / Johan Setia Mahkota',
                'prefix_title' => null,
                'suffix_title' => 'JMN / JSM',
                'grants_ybhg' => false,
                'display_order' => 6,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Persekutuan',
                'issuer' => 'Kerajaan Persekutuan (YDPA)',
                'scope_level' => 'Persekutuan (Kepujian/Tanpa Gelaran)',
                'award_name' => 'Kesatria Mangku Negara / Kesatria Setia Diraja',
                'prefix_title' => null,
                'suffix_title' => 'KMN / KSD',
                'grants_ybhg' => false,
                'display_order' => 7,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Persekutuan',
                'issuer' => 'Kerajaan Persekutuan (YDPA)',
                'scope_level' => 'Persekutuan (Kepujian/Tanpa Gelaran)',
                'award_name' => 'Ahli Mangku Negara / Bentara Setia Diraja',
                'prefix_title' => null,
                'suffix_title' => 'AMN / BSD',
                'grants_ybhg' => false,
                'display_order' => 8,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Persekutuan',
                'issuer' => 'Kerajaan Persekutuan (YDPA)',
                'scope_level' => 'Persekutuan (Pingat Prestasi/Perkhidmatan)',
                'award_name' => 'Pingat Pangkuan Negara',
                'prefix_title' => null,
                'suffix_title' => 'PPN',
                'grants_ybhg' => false,
                'display_order' => 9,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Wilayah Persekutuan',
                'issuer' => 'Wilayah Persekutuan (YDPA)',
                'scope_level' => 'Wilayah Persekutuan',
                'award_name' => 'Seri Utama Mahkota Wilayah (SUMW)',
                'prefix_title' => 'Datuk Seri Utama',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 10,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Wilayah Persekutuan',
                'issuer' => 'Wilayah Persekutuan (YDPA)',
                'scope_level' => 'Wilayah Persekutuan',
                'award_name' => 'Seri Mahkota Wilayah (SMW)',
                'prefix_title' => 'Datuk Seri',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 11,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Wilayah Persekutuan',
                'issuer' => 'Wilayah Persekutuan (YDPA)',
                'scope_level' => 'Wilayah Persekutuan',
                'award_name' => 'Panglima Mahkota Wilayah (PMW)',
                'prefix_title' => 'Datuk',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 12,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Wilayah Persekutuan',
                'issuer' => 'Wilayah Persekutuan (YDPA)',
                'scope_level' => 'Wilayah Persekutuan (Kepujian/Tanpa Gelaran)',
                'award_name' => 'Johan Mahkota Wilayah',
                'prefix_title' => null,
                'suffix_title' => 'JMW',
                'grants_ybhg' => false,
                'display_order' => 13,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Wilayah Persekutuan',
                'issuer' => 'Wilayah Persekutuan (YDPA)',
                'scope_level' => 'Wilayah Persekutuan (Kepujian/Tanpa Gelaran)',
                'award_name' => 'Kesatria Mahkota Wilayah',
                'prefix_title' => null,
                'suffix_title' => 'KMW',
                'grants_ybhg' => false,
                'display_order' => 14,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Wilayah Persekutuan',
                'issuer' => 'Wilayah Persekutuan (YDPA)',
                'scope_level' => 'Wilayah Persekutuan (Kepujian/Tanpa Gelaran)',
                'award_name' => 'Ahli Mahkota Wilayah',
                'prefix_title' => null,
                'suffix_title' => 'AMW',
                'grants_ybhg' => false,
                'display_order' => 15,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Wilayah Persekutuan',
                'issuer' => 'Wilayah Persekutuan (YDPA)',
                'scope_level' => 'Wilayah Persekutuan (Pingat)',
                'award_name' => 'Pingat Pangkuan Mahkota Wilayah',
                'prefix_title' => null,
                'suffix_title' => 'PPW',
                'grants_ybhg' => false,
                'display_order' => 16,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Melaka',
                'scope_level' => 'Negeri (TYT Yang di-Pertua Negeri)',
                'award_name' => 'Darjah Utama Negeri Melaka (DUNM)',
                'prefix_title' => 'Datuk Seri Utama',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 17,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Melaka',
                'scope_level' => 'Negeri (TYT Yang di-Pertua Negeri)',
                'award_name' => 'Darjah Gemilang Seri Melaka (DGSM)',
                'prefix_title' => 'Datuk Seri',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 18,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Melaka',
                'scope_level' => 'Negeri (TYT Yang di-Pertua Negeri)',
                'award_name' => 'Darjah Cemerlang Seri Melaka (DCSM)',
                'prefix_title' => 'Datuk Wira',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 19,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Melaka',
                'scope_level' => 'Negeri (TYT Yang di-Pertua Negeri)',
                'award_name' => 'Darjah Mulia Seri Melaka (DMSM)',
                'prefix_title' => 'Datuk',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 20,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Melaka',
                'scope_level' => 'Negeri (TYT Yang di-Pertua Negeri)',
                'award_name' => 'Darjah Pangkuan Seri Melaka (DPSM)',
                'prefix_title' => 'Datuk',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 21,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Melaka',
                'scope_level' => 'Negeri (Kepujian/Pingat)',
                'award_name' => 'Darjah Seri Melaka (Darjah & Bintang)',
                'prefix_title' => null,
                'suffix_title' => 'DSM / BCM / BKT / PJK / PBM',
                'grants_ybhg' => false,
                'display_order' => 22,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Kedah',
                'scope_level' => 'Negeri (Sultan Kedah)',
                'award_name' => 'Darjah Seri Setia Diraja Kedah (SSDK)',
                'prefix_title' => 'Dato\' Seri Diraja',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 23,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Kedah',
                'scope_level' => 'Negeri (Sultan Kedah)',
                'award_name' => 'Darjah Gemilang Wira Mahkota Kedah (DGMK)',
                'prefix_title' => 'Dato\' Wira',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 24,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Kedah',
                'scope_level' => 'Negeri (Sultan Kedah)',
                'award_name' => 'Darjah Paduka Mahkota Kedah (DPMK)',
                'prefix_title' => 'Dato\'',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 25,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Kedah',
                'scope_level' => 'Negeri (Kepujian/Pingat)',
                'award_name' => 'Bintang Keberanian / Jasa Kebaktian',
                'prefix_title' => null,
                'suffix_title' => 'SDK / AMK / PCK / BKM / PJK',
                'grants_ybhg' => false,
                'display_order' => 26,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Selangor',
                'scope_level' => 'Negeri (Sultan Selangor)',
                'award_name' => 'Darjah Kebesaran Seri Paduka Mahkota Selangor (SPMS)',
                'prefix_title' => 'Dato\' Seri',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 27,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Selangor',
                'scope_level' => 'Negeri (Sultan Selangor)',
                'award_name' => 'Darjah Kebesaran Dato\' Paduka Mahkota Selangor (DPMS)',
                'prefix_title' => 'Dato\'',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 28,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Selangor',
                'scope_level' => 'Negeri (Kepujian/Pingat)',
                'award_name' => 'Setia Mahkota Selangor / Ahli Mahkota Selangor',
                'prefix_title' => null,
                'suffix_title' => 'SMS / AMS / BKS / PJK',
                'grants_ybhg' => false,
                'display_order' => 29,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Johor',
                'scope_level' => 'Negeri (Sultan Johor)',
                'award_name' => 'Darjah Mahkota Johor Yang Amat Mulia (SPMJ)',
                'prefix_title' => 'Dato\'',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 30,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Johor',
                'scope_level' => 'Negeri (Sultan Johor)',
                'award_name' => 'Darjah Mahkota Johor Yang Amat Mulia Pangkat Dua (DPMJ)',
                'prefix_title' => 'Dato\'',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 31,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Johor',
                'scope_level' => 'Negeri (Kepujian/Pingat)',
                'award_name' => 'Setia Mahkota Johor / Pingat Sultan Ibrahim',
                'prefix_title' => null,
                'suffix_title' => 'SMJ / PSI / PIS',
                'grants_ybhg' => false,
                'display_order' => 32,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Perak',
                'scope_level' => 'Negeri (Sultan Perak)',
                'award_name' => 'Darjah Seri Paduka Cura Si Manja Kini (SPCM)',
                'prefix_title' => 'Dato\' Seri',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 33,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Perak',
                'scope_level' => 'Negeri (Sultan Perak)',
                'award_name' => 'Darjah Paduka Mahkota Perak (DPMP)',
                'prefix_title' => 'Dato\'',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 34,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Perak',
                'scope_level' => 'Negeri (Kepujian/Pingat)',
                'award_name' => 'Paduka Mahkota Perak / Pingat Jasa Kebaktian',
                'prefix_title' => null,
                'suffix_title' => 'PMP / AMP / PPT / PJK',
                'grants_ybhg' => false,
                'display_order' => 35,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Pahang',
                'scope_level' => 'Negeri (Sultan Pahang)',
                'award_name' => 'Darjah Sri Sultan Ahmad Shah Pahang (SSAP)',
                'prefix_title' => 'Dato\' Sri',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 36,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Pahang',
                'scope_level' => 'Negeri (Sultan Pahang)',
                'award_name' => 'Darjah Indera Mahkota Pahang (DIMP)',
                'prefix_title' => 'Dato\'',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 37,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Pahang',
                'scope_level' => 'Negeri (Kepujian/Pingat)',
                'award_name' => 'Setia Mahkota Pahang / Ahli Mahkota Pahang',
                'prefix_title' => null,
                'suffix_title' => 'SMP / AMP / PKC / PKT / PJK',
                'grants_ybhg' => false,
                'display_order' => 38,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Pulau Pinang',
                'scope_level' => 'Negeri (TYT Yang di-Pertua Negeri)',
                'award_name' => 'Darjah Panglima Pangkuan Negeri (DPPN)',
                'prefix_title' => 'Dato\' Seri',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 39,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Pulau Pinang',
                'scope_level' => 'Negeri (TYT Yang di-Pertua Negeri)',
                'award_name' => 'Darjah Setia Pangkuan Negeri (DSPN)',
                'prefix_title' => 'Dato\'',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 40,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Pulau Pinang',
                'scope_level' => 'Negeri (Kepujian/Pingat)',
                'award_name' => 'Bintang Cemerlang Negeri / Pingat Kelakuan Terpuji',
                'prefix_title' => null,
                'suffix_title' => 'DJN / BCN / PKT / PJK / PJM',
                'grants_ybhg' => false,
                'display_order' => 41,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Sabah',
                'scope_level' => 'Negeri (TYT Yang di-Pertua Negeri)',
                'award_name' => 'Seri Panglima Darjah Kinabalu (SPDK)',
                'prefix_title' => 'Datuk Seri Panglima',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 42,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Sabah',
                'scope_level' => 'Negeri (TYT Yang di-Pertua Negeri)',
                'award_name' => 'Panglima Gemilang Darjah Kinabalu (PGDK)',
                'prefix_title' => 'Datuk',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 43,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Sabah',
                'scope_level' => 'Negeri (Kepujian/Pingat)',
                'award_name' => 'Ahli Setia Darjah Kinabalu / Bintang Setia Kinabalu',
                'prefix_title' => null,
                'suffix_title' => 'ASDK / ADK / BSK / BK',
                'grants_ybhg' => false,
                'display_order' => 44,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Sarawak',
                'scope_level' => 'Negeri (TYT Yang di-Pertua Negeri)',
                'award_name' => 'Datuk Patinggi Bintang Kenyalang (DP)',
                'prefix_title' => 'Datuk Patinggi',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 45,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Sarawak',
                'scope_level' => 'Negeri (TYT Yang di-Pertua Negeri)',
                'award_name' => 'Panglima Negara Bintang Sarawak (PNBS)',
                'prefix_title' => 'Dato Sri',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 46,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Sarawak',
                'scope_level' => 'Negeri (TYT Yang di-Pertua Negeri)',
                'award_name' => 'Panglima Gemilang Bintang Kenyalang (PGBK)',
                'prefix_title' => 'Datuk',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 47,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Sarawak',
                'scope_level' => 'Negeri (Kepujian/Pingat)',
                'award_name' => 'Johan Bintang Sarawak / Ahli Bintang Kenyalang',
                'prefix_title' => null,
                'suffix_title' => 'JBS / JBK / PBS / PBK / PPB',
                'grants_ybhg' => false,
                'display_order' => 48,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Terengganu',
                'scope_level' => 'Negeri (Sultan Terengganu)',
                'award_name' => 'Seri Setia Sultan Mizan Zainal Abidin Terengganu (SSMZ)',
                'prefix_title' => 'Dato\' Seri Diraja',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 49,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Terengganu',
                'scope_level' => 'Negeri (Sultan Terengganu)',
                'award_name' => 'Seri Paduka Mahkota Terengganu (SPMT)',
                'prefix_title' => 'Dato\' Seri',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 50,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Terengganu',
                'scope_level' => 'Negeri (Sultan Terengganu)',
                'award_name' => 'Dato\' Paduka Mahkota Terengganu (DPMT)',
                'prefix_title' => 'Dato\'',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 51,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Terengganu',
                'scope_level' => 'Negeri (Sultan Terengganu)',
                'award_name' => 'Dato\' Setia Sultan Mizan Zainal Abidin Terengganu (DSMZ)',
                'prefix_title' => 'Dato\'',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 52,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Terengganu',
                'scope_level' => 'Negeri (Kepujian/Pingat)',
                'award_name' => 'Setia Mahkota Terengganu / Pingat Jasa Kebaktian',
                'prefix_title' => null,
                'suffix_title' => 'SMT / AMZ / AMT / PJC / PJK / BLB',
                'grants_ybhg' => false,
                'display_order' => 53,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Sembilan',
                'scope_level' => 'Negeri (YDP Besar Negeri Sembilan)',
                'award_name' => 'Darjah Seri Utama Negeri Sembilan (SUNS)',
                'prefix_title' => 'Dato\' Seri Utama',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 54,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Sembilan',
                'scope_level' => 'Negeri (YDP Besar Negeri Sembilan)',
                'award_name' => 'Darjah Seri Setia Negeri Sembilan Yang Amat Cemerlang (SSNS)',
                'prefix_title' => 'Dato\' Seri',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 55,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Sembilan',
                'scope_level' => 'Negeri (YDP Besar Negeri Sembilan)',
                'award_name' => 'Darjah Dato\' Paduka Negeri Sembilan (DPNS)',
                'prefix_title' => 'Dato\'',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 56,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Sembilan',
                'scope_level' => 'Negeri (YDP Besar Negeri Sembilan)',
                'award_name' => 'Darjah Setia Bakti Negeri Sembilan (DBNS)',
                'prefix_title' => 'Dato\'',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 57,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Sembilan',
                'scope_level' => 'Negeri (Kepujian/Pingat)',
                'award_name' => 'Darjah Pekerti Terpilih / Pingat Jasa Kebaktian',
                'prefix_title' => null,
                'suffix_title' => 'DPT / DNS / ANS / PMC / PJK / PKL',
                'grants_ybhg' => false,
                'display_order' => 58,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Kelantan',
                'scope_level' => 'Negeri (Sultan Kelantan)',
                'award_name' => 'Darjah Kebesaran Mahkota Kelantan Yang Amat Mulia (SPMK)',
                'prefix_title' => 'Dato\'',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 59,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Kelantan',
                'scope_level' => 'Negeri (Sultan Kelantan)',
                'award_name' => 'Darjah Kebesaran Jiwa Mahkota Kelantan Yang Amat Mulia (SJMK)',
                'prefix_title' => 'Dato\'',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 60,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Kelantan',
                'scope_level' => 'Negeri (Sultan Kelantan)',
                'award_name' => 'Darjah Kebesaran Setia Mahkota Kelantan Yang Amat Terbilang (SPSK)',
                'prefix_title' => 'Dato\'',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 61,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Kelantan',
                'scope_level' => 'Negeri (Sultan Kelantan)',
                'award_name' => 'Darjah Kebesaran Jasa Mahkota Kelantan Yang Amat Setia (SPJK)',
                'prefix_title' => 'Dato\'',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 62,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Kelantan',
                'scope_level' => 'Negeri (Sultan Kelantan)',
                'award_name' => 'Dato\' Paduka (DPMK / DJMK / DPSK / DPJK)',
                'prefix_title' => 'Dato\'',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 63,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Kelantan',
                'scope_level' => 'Negeri (Kepujian/Pingat)',
                'award_name' => 'Bentara Setia / Ahli Mahkota / Seri Mahkota',
                'prefix_title' => null,
                'suffix_title' => 'SMK / SK / AK / PS / PT / PPB',
                'grants_ybhg' => false,
                'display_order' => 64,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Perlis',
                'scope_level' => 'Negeri (Raja Perlis)',
                'award_name' => 'Darjah Kerabat Mahkota Perlis Yang Amat Dihormati (SPMP)',
                'prefix_title' => 'Dato\' Seri',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 65,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Perlis',
                'scope_level' => 'Negeri (Raja Perlis)',
                'award_name' => 'Darjah Setia Tuanku Syed Sirajuddin Jamalullail (SSSJ)',
                'prefix_title' => 'Dato\' Seri Diraja',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 66,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Perlis',
                'scope_level' => 'Negeri (Raja Perlis)',
                'award_name' => 'Darjah Dato\' Paduka Mahkota Perlis (DPMP)',
                'prefix_title' => 'Dato\'',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 67,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Perlis',
                'scope_level' => 'Negeri (Raja Perlis)',
                'award_name' => 'Darjah Dato\' Wira Tuanku Syed Sirajuddin Jamalullail (DWSJ)',
                'prefix_title' => 'Dato\' Wira',
                'suffix_title' => null,
                'grants_ybhg' => true,
                'display_order' => 68,
                'is_active' => true,
            ],
            [
                'issuer_category' => 'Negeri',
                'issuer' => 'Negeri Perlis',
                'scope_level' => 'Negeri (Kepujian/Pingat)',
                'award_name' => 'Setia Mahkota Perlis / Pingat Jasa Kebaktian',
                'prefix_title' => null,
                'suffix_title' => 'SMP / SSP / AMP / PJK / PJB / PPL',
                'grants_ybhg' => false,
                'display_order' => 69,
                'is_active' => true,
            ],
        ];

        foreach ($items as $item) {
            HonoraryTitleMaster::updateOrCreate(
                [
                    'issuer' => $item['issuer'],
                    'scope_level' => $item['scope_level'],
                    'award_name' => $item['award_name'],
                ],
                $item
            );
        }
    }
}
