<?php

namespace Database\Seeders;

use App\Models\ProfessionalRecognitionMaster;
use Illuminate\Database\Seeder;

class ProfessionalRecognitionMasterSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'regulator_category' => 'Badan Statutori Utama Berkecuali',
                'issuer' => 'Lembaga Jurutera Malaysia (BEM)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Jurutera Siswazah (Graduate Engineer)',
                'prefix_title' => null,
                'suffix_title' => null,
                'prefix_priority' => null,
                'display_order' => 1,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Statutori Utama Berkecuali',
                'issuer' => 'Lembaga Jurutera Malaysia (BEM)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Teknologis Kejuruteraan (Engineering Technologist)',
                'prefix_title' => null,
                'suffix_title' => 'Eng. Tech.',
                'prefix_priority' => null,
                'display_order' => 2,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Statutori Utama Berkecuali',
                'issuer' => 'Lembaga Jurutera Malaysia (BEM)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Pemeriksa Diari / Inspektor Tapak (Inspector of Works)',
                'prefix_title' => null,
                'suffix_title' => 'IOW',
                'prefix_priority' => null,
                'display_order' => 3,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Statutori Utama Berkecuali',
                'issuer' => 'Lembaga Jurutera Malaysia (BEM)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Jurutera Profesional (Professional Engineer)',
                'prefix_title' => 'Ir.',
                'suffix_title' => 'P.Eng.',
                'prefix_priority' => 30,
                'display_order' => 4,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Statutori Utama Berkecuali',
                'issuer' => 'Lembaga Jurutera Malaysia (BEM)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Jurutera Profesional dengan Sijil Amalan (PEPC)',
                'prefix_title' => 'Ir.',
                'suffix_title' => 'P.Eng.',
                'prefix_priority' => 30,
                'display_order' => 5,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Statutori Utama Berkecuali',
                'issuer' => 'Lembaga Jurutera Malaysia (BEM)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Pemeriksa Bertauliah (Accredited Checker)',
                'prefix_title' => 'Ir.',
                'suffix_title' => 'P.Eng.',
                'prefix_priority' => 30,
                'display_order' => 6,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Statutori Utama Berkecuali',
                'issuer' => 'BEM (melalui ACPECC)',
                'registration_scope' => 'Antarabangsa',
                'professional_level' => 'ASEAN Chartered Professional Engineer',
                'prefix_title' => null,
                'suffix_title' => 'ACPE',
                'prefix_priority' => null,
                'display_order' => 7,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Statutori Utama Berkecuali',
                'issuer' => 'BEM (melalui ACPECC)',
                'registration_scope' => 'Antarabangsa',
                'professional_level' => 'Registered Foreign Professional Engineer',
                'prefix_title' => null,
                'suffix_title' => 'RFPE',
                'prefix_priority' => null,
                'display_order' => 8,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Statutori Utama Berkecuali',
                'issuer' => 'BEM (melalui IEA)',
                'registration_scope' => 'Antarabangsa',
                'professional_level' => 'International Professional Engineer',
                'prefix_title' => null,
                'suffix_title' => 'IntPE (MY)',
                'prefix_priority' => null,
                'display_order' => 9,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Statutori Utama Berkecuali',
                'issuer' => 'BEM (melalui IEA)',
                'registration_scope' => 'Antarabangsa',
                'professional_level' => 'APEC Engineer',
                'prefix_title' => null,
                'suffix_title' => 'APEC Eng.',
                'prefix_priority' => null,
                'display_order' => 10,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Statutori Utama Berkecuali',
                'issuer' => 'Lembaga Arkitek Malaysia (LAM)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Arkitek Profesional (Professional Architect)',
                'prefix_title' => 'Ar.',
                'suffix_title' => null,
                'prefix_priority' => 31,
                'display_order' => 11,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Statutori Utama Berkecuali',
                'issuer' => 'Lembaga Juruukur Bahan (BQSM)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Juruukur Bahan Profesional (Professional Quantity Surveyor)',
                'prefix_title' => 'Sr.',
                'suffix_title' => null,
                'prefix_priority' => 32,
                'display_order' => 12,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Ikhtisas Seterusnya',
                'issuer' => 'Lembaga Teknologis Malaysia (MBOT)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Teknologis Berijazah (Graduate Technologist)',
                'prefix_title' => null,
                'suffix_title' => null,
                'prefix_priority' => null,
                'display_order' => 13,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Ikhtisas Seterusnya',
                'issuer' => 'Lembaga Teknologis Malaysia (MBOT)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Juruteknik Berkelayakan (Qualified Technician)',
                'prefix_title' => null,
                'suffix_title' => null,
                'prefix_priority' => null,
                'display_order' => 14,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Ikhtisas Seterusnya',
                'issuer' => 'Lembaga Teknologis Malaysia (MBOT)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Teknologis Profesional (Professional Technologist)',
                'prefix_title' => 'Ts.',
                'suffix_title' => 'P.Tech.',
                'prefix_priority' => 40,
                'display_order' => 15,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Ikhtisas Seterusnya',
                'issuer' => 'Lembaga Teknologis Malaysia (MBOT)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Juruteknik Bertauliah (Certified Technician)',
                'prefix_title' => 'Tc.',
                'suffix_title' => 'C.Tech.',
                'prefix_priority' => 41,
                'display_order' => 16,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Ikhtisas Seterusnya',
                'issuer' => 'MBOT (melalui ATER)',
                'registration_scope' => 'Antarabangsa',
                'professional_level' => 'ASEAN Chartered Professional Technologist',
                'prefix_title' => null,
                'suffix_title' => 'ACPT',
                'prefix_priority' => null,
                'display_order' => 17,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Ikhtisas Seterusnya',
                'issuer' => 'MBOT (melalui ATER)',
                'registration_scope' => 'Antarabangsa',
                'professional_level' => 'ASEAN Certified Advanced Technician',
                'prefix_title' => null,
                'suffix_title' => 'ACAT',
                'prefix_priority' => null,
                'display_order' => 18,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Ikhtisas Seterusnya',
                'issuer' => 'Pertubuhan Perancang Malaysia (MIP)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Ahli Korporat / Perancang Bandar Profesional',
                'prefix_title' => 'Pmr. / TPr.',
                'suffix_title' => null,
                'prefix_priority' => 80,
                'display_order' => 19,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Ikhtisas Seterusnya',
                'issuer' => 'Royal Institution of Surveyors Malaysia (RISM - BS Division)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Juruukur Bangunan Bertauliah (Registered Building Surveyor)',
                'prefix_title' => 'Br.',
                'suffix_title' => null,
                'prefix_priority' => 50,
                'display_order' => 20,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Ikhtisas Seterusnya',
                'issuer' => 'Institution of Geospatial and Remote Sensing Malaysia (IGRSM)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Ahli Profesional Geospatial (Professional Geospatialist)',
                'prefix_title' => 'Gs.',
                'suffix_title' => null,
                'prefix_priority' => 60,
                'display_order' => 21,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Badan Ikhtisas Seterusnya',
                'issuer' => 'Malaysian Association of Project Management (MAPM)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Pengurus Projek Profesional (Professional Project Manager)',
                'prefix_title' => 'PMr.',
                'suffix_title' => null,
                'prefix_priority' => 70,
                'display_order' => 22,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Akademik Tertinggi',
                'issuer' => 'Majlis Perubatan Malaysia (MMC)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Pegawai Perubatan / Pengamal Perubatan Berdaftar (Medical Practitioner)',
                'prefix_title' => 'Dr.',
                'suffix_title' => null,
                'prefix_priority' => 20,
                'display_order' => 23,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Akademik Tertinggi',
                'issuer' => 'Majlis Pergigian Malaysia (MDC)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Pengamal Pergigian Berdaftar (Dental Practitioner)',
                'prefix_title' => 'Dr.',
                'suffix_title' => null,
                'prefix_priority' => 20,
                'display_order' => 24,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Akademik Tertinggi',
                'issuer' => 'Lembaga Doktor Veterinar Malaysia (MVC)',
                'registration_scope' => 'Domestik',
                'professional_level' => 'Doktor Perubatan Veterinar (Veterinary Surgeon)',
                'prefix_title' => 'Dr.',
                'suffix_title' => null,
                'prefix_priority' => 20,
                'display_order' => 25,
                'is_active' => true,
            ],
            [
                'regulator_category' => 'Akademik Tertinggi',
                'issuer' => 'Institusi Pengajian Tinggi (IPT / Universiti)',
                'registration_scope' => 'Akademik',
                'professional_level' => 'Pemegang Ijazah Doktor Falsafah (Doctor of Philosophy / PhD)',
                'prefix_title' => 'Dr.',
                'suffix_title' => 'PhD',
                'prefix_priority' => 20,
                'display_order' => 26,
                'is_active' => true,
            ],
        ];

        foreach ($items as $item) {
            ProfessionalRecognitionMaster::updateOrCreate(
                [
                    'issuer' => $item['issuer'],
                    'registration_scope' => $item['registration_scope'],
                    'professional_level' => $item['professional_level'],
                ],
                $item
            );
        }
    }
}
